### ISSUE TITLE
Monthly UTZ goes to 100% after hitting 'Save'

### ISSUE THREAD

**Issue by mathiassiig** [futurice/hours-ui#56] opened 2017-04-18 12:52 UTC
Refreshing the page calculates the monthly UTZ correctly

**Comment by mathiassiig** [comment] 2017-04-18 13:09
More on this... when hitting 'Load more', it sets the UTZ rate of the current month to 0%

**Comment by phadej** [comment] 2017-04-26 11:22
duplicate of #43

**Closed by phadej** 2017-04-26 11:22 UTC
Labels: duplicate, type:bug
